### ISSUE TITLE
Unable to fetch content files still

### ISSUE THREAD

**Issue by DLinser** [meta-quest/ProjectFlowerbed#4]
the way to get content files still unable to fetch by donload zip

**Comment by dmliao** [comment]
Hello! 

I've confirmed that if you `Download ZIP` from the Github page, then the content files under LFS don't expand properly into their full forms. It looks like this is the default in Github and there is a [setting](https://github.com/git-lfs/git-lfs/issues/903) to change that behavior in the repository, but that will have to wait for a few days since I don't have access to that setting right now.

In the meantime, **cloning** the repository using git will populate the content files correctly.
