### ISSUE TITLE
Uncaught (in promise) Error: Missing KTX 2.0 identifier.

### ISSUE THREAD

**Issue by DLinser** [meta-quest/ProjectFlowerbed#5]
Hello, I can not fetch the ["three": "https://github.com/snagy/three.js-1.git#r144-merge#6fc27ea"] when I used the latest version of Three, it didn't work. And show error like [Uncaught (in promise) Error: Missing KTX 2.0 identifier.]

**Comment by snagy** [comment]
Hi!

I actually got a local fork building with github actions and ran into both of these issues.

For the first one, I had two issues and I don't remember which one actually fixed it:
1) Using node.js version 14.x didn't work, but using 16.x did work.  If you aren't already using 16+, try upgrading node.
2) Make sure you're using "yarn install" instead of "npm install".

I think those two things should hopefully get you past the first error.

For the second error, make sure you've got your git LFS set up and are properly syncing those assets - if you look in your local directory and your ktx2 files are less than like 200 bytes, you might need to 'git lfs pull' to download the assets.

Finally, if you visited your site without the LFS assets, the caching mechanism might be loading the small files.  (we should file an issue to ensure we don't cache files that are abnormally small)

You can fix this by going into your chrome dev tools, then opening up the "applications" tab and finding the section on the left labeled "cache storage" (it might be in a section labeled "Cache" or a section labeled "Storage" depending on your chrome version) and then right click and delete the "flowerbed-asset-cache" listed there.  If you're trying to do this on a Quest, you can connect via USB and then use chrome://inspect/#devices to find the flowerbed tab, click "inspect" and then go through the same steps.

**Comment by DLinser** [comment]
Thank you for your reply. It has been resolved  @snagy

**Comment by tjt740** [comment]
How did you solve it，excuse me

**Comment by jonititan** [comment]
> How did you solve it，excuse me

Git LFS needs to be installed for the large files to be pulled down during git clone
https://packagecloud.io/github/git-lfs/install

install that, then clone the repository, and then follow the instructions in the readme.  It all worked for me after that.

**Comment by ipeakermit** [comment]
Might want to add the "git-lfs" dependency to the README, I got caught just now
